version: '3.3'


services:
  psql:
    image: postgres:13.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=sdb_homework
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - "db-data:/var/lib/postgresql/data"
volumes:
  db-data: