"""3

Revision ID: 3a82615d8f3a
Revises: 60feda05ef56
Create Date: 2022-08-07 15:22:16.932831

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '3a82615d8f3a'
down_revision = '60feda05ef56'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver', sa.Column('full_name', sa.VARCHAR(length=255), nullable=True))
    op.execute("UPDATE driver SET full_name = name || ' ' || last_name")
    op.alter_column('driver', 'full_name', nullable=False)
    op.drop_column('driver', 'name')
    op.drop_column('driver', 'last_name')
    op.alter_column('spaceship_manufacturer', 'nasdaq_code', new_column_name='moex_code')
    op.execute("UPDATE spaceship_manufacturer SET moex_code = moex_code || '_ru' ")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver', sa.Column("name", sa.VARCHAR(50), nullable=True))
    op.add_column('driver', sa.Column("last_name", sa.VARCHAR(50), nullable=True))
    op.execute("UPDATE driver SET name = split_part(full_name::TEXT,' ', 1)")
    op.execute("UPDATE driver SET last_name = split_part(full_name::TEXT,' ', 2)")
    op.alter_column('driver', 'name', nullable=False)
    op.drop_column('driver', 'full_name')
    op.alter_column('spaceship_manufacturer', 'moex_code', new_column_name='nasdaq_code')
    op.execute("UPDATE spaceship_manufacturer SET nasdaq_code = split_part(nasdaq_code::TEXT,'_ru', 1)")
    # ### end Alembic commands ###
