"""empty message

Revision ID: 001cfcd6d2b0
Revises: e4aa3eebebf7
Create Date: 2022-08-14 01:24:59.582480

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "001cfcd6d2b0"
down_revision = "e4aa3eebebf7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk__bookmark__owner_id__user", "bookmark", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk__bookmark__owner_id__user"),
        "bookmark",
        "user",
        ["owner_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk__bookmark__owner_id__user"), "bookmark", type_="foreignkey")
    op.create_foreign_key(
        "fk__bookmark__owner_id__user",
        "bookmark",
        "user",
        ["owner_id"],
        ["id"],
        onupdate="SET NULL",
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###
