"""empty message

Revision ID: 970d84738c0b
Revises: 
Create Date: 2022-06-23 10:32:29.561485

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = "970d84738c0b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp";')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "url_storage",
        sa.Column("dt_created", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("uuid_generate_v4()"), nullable=False),
        sa.Column("long_url", sa.TEXT(), nullable=False),
        sa.Column("short_url", sa.TEXT(), nullable=False),
        sa.Column(
            "secret_key", postgresql.UUID(as_uuid=True), server_default=sa.text("uuid_generate_v4()"), nullable=True
        ),
        sa.Column("number_of_clicks", sa.INTEGER(), server_default=sa.text("0"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__url_storage")),
        sa.UniqueConstraint("id", name=op.f("uq__url_storage__id")),
    )
    op.create_index(op.f("ix__url_storage__long_url"), "url_storage", ["long_url"], unique=True)
    op.create_index(op.f("ix__url_storage__secret_key"), "url_storage", ["secret_key"], unique=True)
    op.create_index(op.f("ix__url_storage__short_url"), "url_storage", ["short_url"], unique=True)
    op.create_unique_constraint(op.f("uq__url_storage__short_url"), "url_storage", ["short_url"])
    op.create_unique_constraint(op.f("uq__url_storage__long_url"), "url_storage", ["long_url"])
    op.create_unique_constraint(op.f("uq__url_storage__id"), "url_storage", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq__url_storage__id"), "url_storage", type_="unique")
    op.drop_constraint(op.f("uq__url_storage__long_url"), "url_storage", type_="unique")
    op.drop_constraint(op.f("uq__url_storage__short_url"), "url_storage", type_="unique")
    op.drop_index(op.f("ix__url_storage__short_url"), table_name="url_storage")
    op.drop_index(op.f("ix__url_storage__secret_key"), table_name="url_storage")
    op.drop_index(op.f("ix__url_storage__long_url"), table_name="url_storage")
    op.drop_table("url_storage")
    # ### end Alembic commands ###
