"""empty message

Revision ID: 1093767001ca
Revises: 3a1f699131ef
Create Date: 2022-07-27 08:12:02.671045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1093767001ca'
down_revision = '3a1f699131ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url_storage', sa.Column('number_of_use_qr_code', sa.INTEGER(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('url_storage', 'number_of_use_qr_code')
    # ### end Alembic commands ###
