"""empty message

Revision ID: 3a1f699131ef
Revises: 970d84738c0b
Create Date: 2022-07-26 06:44:32.623743

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = "3a1f699131ef"
down_revision = "970d84738c0b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "url_storage",
        sa.Column(
            "dt_expired",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("NOW() + interval '100 years'"),
            nullable=False,
        ),
    )
    op.drop_constraint("uq__url_storage__long_url", "url_storage", type_="unique")
    op.drop_constraint("uq__url_storage__short_url", "url_storage", type_="unique")
    op.drop_index("ix__url_storage__long_url", table_name="url_storage")
    op.create_index(op.f("ix__url_storage__long_url"), "url_storage", ["long_url"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix__url_storage__long_url"), table_name="url_storage")
    op.create_index("ix__url_storage__long_url", "url_storage", ["long_url"], unique=False)
    op.create_unique_constraint("uq__url_storage__short_url", "url_storage", ["short_url"])
    op.create_unique_constraint("uq__url_storage__long_url", "url_storage", ["long_url"])
    op.drop_column("url_storage", "dt_expired")
    # ### end Alembic commands ###
